### ISSUE TITLE
Annotation links appear to be broken

### ISSUE THREAD

**Issue by h3xstream** [jwgmeligmeyling/spotbugs-github-action#5]
I have tested the GH action on my repository.
The link to the annotations are not working. It might be because the annotation are created in files that are not part of the PR integrated.
https://github.com/find-sec-bugs/find-sec-bugs/actions/runs/226494945

**Comment by jwgmeligmeyling** [comment]
The links are working, but only for errors introduced in the commit / pull request. Because the file needs to be visible in the diff your looking at.

We by the way do not generate the link. The API only allows us to specify a path to the file relative to the repository root. So theres not much we can do beyond just omitting warnings beyond the touched lines in a commit, which is IMO unpreferable. In particular because Spotbugs has a tendency to put certain errors at the beginning or end of a classfile, which is almost never touched in a file. And certain changes might produce violations at a completely different line (i.e. a variable that becomes unused).

For any project that is really strict about either resolving or annotating Spotbugs issues (or tweaking configuration), this shouldnt be a problem anymore shortly after using this Action.

**Comment by jwgmeligmeyling** [comment]
Btw, since Spotbugs now supports the SARIF format ( https://github.com/spotbugs/spotbugs/pull/1185 ) , security issues can be pushed to Github in a different manner: https://docs.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/uploading-a-sarif-file-to-github . I didn’t get to try it out yet, but it seems Github is transitioning in that direction for security based static analysis.

**Comment by h3xstream** [comment]
Yep unrelated to this implementation. This is an issue with Github Action.
https://github.community/t/creating-annotations-for-failed-tests-in-files-not-in-the-commit-changeset/17060
