### ISSUE TITLE
HttpError: Resource not accessible by integration

### ISSUE THREAD

**Issue by h3xstream** [jwgmeligmeyling/spotbugs-github-action#6]
Running the action in Pull Request raise an error on with my configuration. The error seems related to permission. 😕 I'm not sure what needs to be fix.
```
> Run jwgmeligmeyling/spotbugs-github-action@master
With the provided path, there will be 1 results uploaded
Creating annotations for /home/runner/work/find-sec-bugs/find-sec-bugs/findsecbugs-plugin/target/spotbugsXml.xml
/home/runner/work/find-sec-bugs/find-sec-bugs/findsecbugs-plugin/target/spotbugsXml.xml has 12 violations
##[error]HttpError: Resource not accessible by integration
```
Configuration:
```yaml
# CI Task using https://github.com/jwgmeligmeyling/spotbugs-github-action

name: Java CI with SpotBugs

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn clean install -DskipTests com.github.spotbugs:spotbugs-maven-plugin:3.1.12:spotbugs
    - uses: jwgmeligmeyling/spotbugs-github-action@master
      with:
        path: '**/spotbugsXml.xml'
```

**Comment by jwgmeligmeyling** [comment]
Did the build take longer than an hour? Afaik the default token for actions expires within an hour. A workaround would be to provide a manually set up key through the configuration options (you could safely store it as a secret).

Did the build take longer than an hour?

**Comment by h3xstream** [comment]
The build took 30s. I am only running compilation. (No test, no special verification)

**Comment by h3xstream** [comment]
I found this thread https://github.com/actions/first-interaction/issues/10 and apparently this is something that have happen to many users.

I'll test this potential fix : https://github.com/actions/first-interaction/issues/10#issuecomment-670968624

**Comment by jwgmeligmeyling** [comment]
Ah yes, it seems Github changed something in their API.

Pull requests by default are built on a merge commit against the target branch. By default we push annotations to this commit, instead of the commit of the head of the branch, because otherwise line numbers misalign (violations won't necessarily appear on the same line in the merge commit as they do in the head commit). As a violation on the wrong line is pointless, we don't generate them there. However, checks on the merge commit won't appear on the commit of the head of the PR, so the report won't become available on the pull request. Instead, an "unnamed workflow" was created for this otherwise invisible commit. It appears that recently Github simply disallowed this situation to happen in the first place, and wants users to use `pull_request_target` instead.

Unfortunately, there appears to be no way for me to reliably detect the head of the branch when the task is building on top of a merge commit. All commit refs available through environment variables and the API, reference this merge commit. This is also what caused #3 .

I also described this issue in the projects README:

> Please note that by default workflows on pull_request events checkout refs/pull/:prNumber/merge instead of the head of the pull request. Due to this, line numbers for the generated violations may not align with the actual line numbers to which they are displayed on the HEAD. As it is, there is not really a sensible way to run this action on the merge commit of the pull request, because the result would be posted to an unnamed workflow for an otherwise invisible commit. Even for pull_request events there is the possibility to checkout the pull request head instead. In order to do so, change your checkout action accordingly:
>
> ```
> - uses: actions/checkout@v2
>   with:
>    ref: ${{ github.event.pull_request.head.sha }}
> ```

That work around is no longer necessary with the availability of `pull_request_target`. Do keep in mind though that `pull_request_target` works, because it no longer checks out the merge commit at all, but checks out the head of the branch. Depending on your situation, this may be completely useless (I don't think its the case for you, as you get pull requests from other remotes for which the push action doesn't get triggered).

Also note, there is little to no use to run this plugin the `pull_request` action. You could potentially use it to check whether _any_ violation exists, and fail the build otherwise, but there is just no way we can reliably map the violations to line numbers.
